[package]
name = "tww"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob="0.3"
itertools="0.10"
rand="0.8"
rand_pcg="0.3"
ez-bitset="0.1"
paste="1.0"
fxhash="0.2"