[package]
name = "tww"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob="0.3"
itertools="0.10"
rand="0.8"
rand_pcg="0.3"
rand_distr="0.4"
paste="1.0"
fxhash="0.2"
rayon="1.6"
bitvec="1.0"
num="0.4"
regex="0.1"
digest = "0.10.0"
sha2 = "0.10.0"
splr = {version="0.17.0", features=["incremental_solver","best_phases_tracking"]}
varisat = "0.2.2"
log = "0.4"
env_logger = "0.9"
structopt="0.3"