[package]
name = "dss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
signal-handling = []

[dependencies]
glob="0.3"
itertools="0.10"
rand="0.8"
rand_pcg="0.3"
rand_distr="0.4"
paste = "1.0"
fxhash="0.2"
rayon="1.6"
regex="0.1"
digest = "0.10.0"
sha2 = "0.10.0"
log = "0.4"
env_logger = "0.9"
structopt="0.3"
ctrlc = { version = "3.1.9", optional = true, features = ["termination"] }
fasthash = "0.4"
stream_bitset = { path="stream-bitset" }
anyhow = "1.0.95"

[profile.release]
#lto="fat"
#codegen-units=1
debug=true

[profile.optil]
inherits="release"
lto="fat"
codegen-units=1
debug=false
panic="abort"
strip=true
