services:
  ds-heuristic:
    build:
      context: .
      dockerfile: pace-eval-ds/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "16GB"
    environment:
      MAX_TIME: 300  #in seconds
      MERCY_TIME: 25 #in seconds
      SOLVER_CMD: "/solver/heuristic"
    volumes:
      - "./output/ds/heuristic:/output"
      - "./instances/ds/heuristic:/instances"

  ds-exact:
    build:
      context: .
      dockerfile: pace-eval-ds/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "16GB"
    environment:
      MAX_TIME: 1800  #in seconds
      MERCY_TIME: 30 #in seconds
      SOLVER_CMD: "/solver/exact"
    volumes:
      - "./output/ds/exact:/output"
      - "./instances/ds/exact:/instances"      