[package]
name = "stream_bitset"
authors = ["Manuel Penschuck <stream-bitset@algorithm.engineering>"]
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"

[dev-dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
